spring:
  cloud:
    gateway:
      routes:
        - id: hello-rest-template
          predicates:
            - Path=/**
          uri: lb://HELLO-REST-TEMPLATE
#          filters:
#            - RewritePath=/api/shop(?<segment>.*),$\{segment}
#            - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, localhost:8080/api/shop
#            - RequestLogger=info,loggerFilter
#            - RequestTime=8:00,17:00
      #discovery:
      #  locator:
      #     enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE