spring:
  cloud:
    gateway:
#      httpclient:
#        wiretap: true
#      httpserver:
#        wiretap: true
      server:
        webmvc:
          routes:
            - id: hello-rest-template
              predicates:
                - Path=/api/hello-rest-template/**
              uri: lb://HELLO-REST-TEMPLATE
              filters:
                - RewritePath=/api/hello-rest-template(?<segment>.*),$\{segment}
#                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, localhost:8080/api/hello-rest-template
    #            - RequestLogger=info,loggerFilter
    #            - RequestTime=8:00,17:00
      #discovery:
      #  locator:
      #     enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE